name: 'Isaac XML File validator'
description: 'Checks the validity of all .xml files inside your mod files for both syntax and usage errors.'
author: "Wofsauge"
inputs:
  rootFolder:  # id of input
    description: 'Folder where the tool should search for .xml files'
    required: true
    default: '**'
runs:
  using: "docker"
  image: "Dockerfile"
