# This workflow will run a test of the action
name: Action test

on:
 - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: wofsauge/Isaac-xmlvalidator-action@main
        with:
          rootFolder: 'vanillaFiles'
