# This workflow will run a test of the action
name: Action test

on:
 - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'test-data' #checkout specific branch
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: wofsauge/Isaac-xmlvalidator-action@main
        with:
          rootFolder: 'vanillaFiles'
